language: php

# Versions of PHP to run.
php:
  - '5.4'
  - '5.5'
  - '5.6'
  - '7.0'
  - '7.1'

script: phpunit

# Customize when the notification emails are sent.
notifications:
  on_success: never
  on_failure: always
